version: "3"

volumes:
  db:
  minio-data:

networks:
  default:
    driver: bridge
    external: false

services:
  web_frontend:
    restart: always
    env_file: .env
    image: node:12.15.0
    working_dir: /app
    volumes:
      - ./web_frontend:/app
    command: "yarn dev"
    ports:
      - 3000:3000
    depends_on:
      - cms
    links:
      - cms

  cms:
    restart: always
    env_file: .env
    build:
      context: ./cms
      dockerfile: Dockerfile
    entrypoint: /usr/bin/entrypoint.sh
    working_dir: /app
    volumes:
      - ./cms:/app
      - ./cms/entrypoint.sh:/usr/bin/entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - minio
    links:
      - postgres
      - minio
    networks:
      - default

  postgres:
    image: postgres:9.6
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file: .env

  minio:
    image: minio/minio:RELEASE.2020-02-07T04-56-50Z
    env_file: .env
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
    command: server /data
